**AND Gate**

In [ ]:
#Imporitng necessary python liabraries
import pandas as pd
import numpy as np

In [ ]:
from keras.models import Sequential  #Sequential model is a linear stack of layers.
from keras.layers.core import Dense  #A Dense layer feeds all outputs from the previous layer to all its neurons, each neuron providing one output to the next layer.

In [ ]:
#Define Gate / Training Data
# 0 0 -> 0
# 0 1 -> 0
# 1 0 -> 0
# 1 1 -> 1

In [ ]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0],[0],[0],[1]])

In [ ]:
#Defining the Model for implementation
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))  #relu -> applies rectified linear unit activation functions
model.add(Dense(1, activation='sigmoid'))   #sigmoid -> applies sigmoid activation function

In [ ]:
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['binary_accuracy']) 
#loss -> mean_squared_error -> The loss is the mean overseen data of the squared differences between true and predicted values.
#Optimiser -> adam -> optimiser that is a stochastic gradient descent method that is based on adpative estimation of first order and second order moments
#metrics -> binary_accuracy -> Calculates how often predictions match binary labels.

In [ ]:
#Training the model
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['binary_accuracy']) 
hist = model.fit(input, output,batch_size=32, epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 734ms/step - loss: 0.2581 - binary_accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2573 - binary_accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2566 - binary_accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2558 - binary_accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2550 - binary_accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2543 - binary_accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2535 - binary_accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2528 - binary_accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2520 - binary_accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 7ms/ste

In [ ]:
#Validation Process
print("Round off Values: \n",model.predict(input).round())
print("Actual·Values:·\n",model.predict(input))

Round off Values: 
 [[0.]
 [0.]
 [0.]
 [1.]]
Actual·Values:·
 [[0.43294615]
 [0.38521567]
 [0.45730323]
 [0.53086954]]


**OR Gate using 4 Layer Keras**


In [19]:
import numpy as np

In [20]:
from keras.models import Sequential
from keras.layers.core import Dense

In [21]:
#Define Gate / Training Data
# 0 0 -> 0
# 0 1 -> 1
# 1 0 -> 1
# 1 1 -> 1

In [30]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0],[1],[1],[1]])

In [31]:
#Defining Model
model = Sequential()
model.add(Dense(2, input_dim=2, activation='tanh')) #Tanh activation function also knows as Tangent Hyperbolic function.
model.add(Dense(2, activation='tanh'))
model.add(Dense(1, activation='sigmoid')) #The sigmoid activation function. The input to the function is transformed into a value between 0.0 and 1.0

In [32]:
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['binary_accuracy'])
hist = model.fit(input, output,batch_size=32, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 394ms/step - loss: 0.2970 - binary_accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2957 - binary_accuracy: 0.2500
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2944 - binary_accuracy: 0.2500
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2931 - binary_accuracy: 0.2500
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2918 - binary_accuracy: 0.2500
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 0.2905 - binary_accuracy: 0.2500
Epoch 7/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2892 - binary_accuracy: 0.2500
Epoch 8/100
1/1 [==============================] - 0s 10ms/step - loss: 0.2880 - binary_accuracy: 0.2500
Epoch 9/100
1/1 [==============================] - 0s 8ms/step - loss: 0.2867 - binary_accuracy: 0.2500
Epoch 10/100
1/1 [==============================] - 0s 15ms/s

In [33]:
print("Round off Values: \n",model.predict(input).round())
print("Actual Values: \n",model.predict(input))

Round off Values: 
 [[1.]
 [1.]
 [1.]
 [1.]]
Actual Values: 
 [[0.594401 ]
 [0.5404893]
 [0.6767299]
 [0.6225923]]


**XOR Gate using 3 Layer Keras**

In [27]:
import numpy as np

In [28]:
from keras.models import Sequential
from keras.layers.core import Dense

In [29]:
#Define Gate / Training Data
# 0 0 -> 0
# 0 1 -> 1
# 1 0 -> 1
# 1 1 -> 0

In [34]:
input = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0],[1],[1],[0]])

In [35]:
model = Sequential()
model.add(Dense(16, input_dim=2, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [37]:
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['binary_accuracy'])
model.fit(input, output, epochs=6000, verbose=2)

Streaming output truncated to the last 5000 lines.
Epoch 3501/6000
1/1 - 0s - loss: 0.0013 - binary_accuracy: 1.0000
Epoch 3502/6000
1/1 - 0s - loss: 0.0013 - binary_accuracy: 1.0000
Epoch 3503/6000
1/1 - 0s - loss: 0.0013 - binary_accuracy: 1.0000
Epoch 3504/6000
1/1 - 0s - loss: 0.0013 - binary_accuracy: 1.0000
Epoch 3505/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3506/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3507/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3508/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3509/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3510/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3511/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3512/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3513/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3514/6000
1/1 - 0s - loss: 0.0012 - binary_accuracy: 1.0000
Epoch 3515/6000
1/1 - 0s 

In [38]:
print("Round off Values: \n",model.predict(input).round())
print("Actual Values: \n",model.predict(input))

Round off Values: 
 [[0.]
 [1.]
 [1.]
 [0.]]
Actual Values: 
 [[0.01452857]
 [0.98613477]
 [0.98616207]
 [0.01383775]]


**NOT Gate**

In [39]:
import numpy as np

In [40]:
from keras.models import Sequential
from keras.layers.core import Dense

In [41]:
#Define Gate / Training Data
# 1 -> 0
# 0 -> 1

In [42]:
input = np.array([[1],[0]])
output = np.array([[0],[1]])

In [43]:
model = Sequential()
model.add(Dense(16, input_dim=1, activation='linear'))
model.add(Dense(1, activation='linear'))

In [45]:
model.compile(loss='mean_squared_error',optimizer='adam', metrics=['binary_accuracy'])
model.fit(input, output, epochs=500, verbose=2)

Epoch 1/500
1/1 - 0s - loss: 0.7724 - binary_accuracy: 0.5000
Epoch 2/500
1/1 - 0s - loss: 0.7586 - binary_accuracy: 0.5000
Epoch 3/500
1/1 - 0s - loss: 0.7450 - binary_accuracy: 0.5000
Epoch 4/500
1/1 - 0s - loss: 0.7316 - binary_accuracy: 0.5000
Epoch 5/500
1/1 - 0s - loss: 0.7184 - binary_accuracy: 0.5000
Epoch 6/500
1/1 - 0s - loss: 0.7055 - binary_accuracy: 0.5000
Epoch 7/500
1/1 - 0s - loss: 0.6928 - binary_accuracy: 0.5000
Epoch 8/500
1/1 - 0s - loss: 0.6803 - binary_accuracy: 0.5000
Epoch 9/500
1/1 - 0s - loss: 0.6680 - binary_accuracy: 0.5000
Epoch 10/500
1/1 - 0s - loss: 0.6560 - binary_accuracy: 0.5000
Epoch 11/500
1/1 - 0s - loss: 0.6442 - binary_accuracy: 0.5000
Epoch 12/500
1/1 - 0s - loss: 0.6326 - binary_accuracy: 0.5000
Epoch 13/500
1/1 - 0s - loss: 0.6213 - binary_accuracy: 0.5000
Epoch 14/500
1/1 - 0s - loss: 0.6101 - binary_accuracy: 0.5000
Epoch 15/500
1/1 - 0s - loss: 0.5993 - binary_accuracy: 0.5000
Epoch 16/500
1/1 - 0s - loss: 0.5886 - binary_accuracy: 0.5000
E

In [46]:
print("Round off Values: \n",model.predict(input).round())
print("Actual Values: \n",model.predict(input))

Round off Values: 
 [[0.]
 [1.]]
Actual Values: 
 [[4.9293041e-05]
 [9.9982643e-01]]
